export interface ValladolidPOI {
  id: string;
  name: string;
  shortName: string;
  category: 'transporte' | 'hospital' | 'comercial' | 'universidad' | 'monumento' | 'deporte' | 'servicios' | 'barrio';
  address: string;
  lat: number;
  lon: number;
  keywords: string[];
  icon: string;
}

export const VALLADOLID_POIS: ValladolidPOI[] = [
  // --- TRANSPORTE ---
  {
    id: 'poi_estacion_campo_grande',
    name: 'Estación de Tren Campo Grande (AVE)',
    shortName: 'Estación de Tren (Campo Grande)',
    category: 'transporte',
    address: 'Calle Recondo s/n',
    lat: 41.6425,
    lon: -4.7291,
    keywords: ['tren', 'ave', 'renfe', 'estacion', 'campo grande', 'viajes', 'recondo'],
    icon: 'Train',
  },
  {
    id: 'poi_estacion_autobuses',
    name: 'Estación de Autobuses de Valladolid',
    shortName: 'Estación de Autobuses',
    category: 'transporte',
    address: 'Calle Puente Colgante 2',
    lat: 41.6422,
    lon: -4.7340,
    keywords: ['autobus', 'autobuses', 'estacion', 'alsa', 'puente colgante', 'viajes'],
    icon: 'Bus',
  },

  // --- HOSPITALES Y SALUD ---
  {
    id: 'poi_hosp_rio_hortega',
    name: 'Hospital Universitario Río Hortega (HURH)',
    shortName: 'Hospital Río Hortega',
    category: 'hospital',
    address: 'Calle Dulzaina 2',
    lat: 41.6268,
    lon: -4.7077,
    keywords: ['hospital', 'rio hortega', 'hurh', 'urgencias', 'dulzaina', 'medico', 'sanidad'],
    icon: 'HeartPulse',
  },
  {
    id: 'poi_hosp_clinico',
    name: 'Hospital Clínico Universitario de Valladolid',
    shortName: 'Hospital Clínico',
    category: 'hospital',
    address: 'Avenida Ramón y Cajal 3',
    lat: 41.6575,
    lon: -4.7176,
    keywords: ['hospital', 'clinico', 'ramon y cajal', 'urgencias', 'medico', 'sanidad', 'universitario'],
    icon: 'HeartPulse',
  },
  {
    id: 'poi_hosp_campo_grande',
    name: 'Hospital Recoletas Campo Grande',
    shortName: 'Hospital Campo Grande',
    category: 'hospital',
    address: 'Plaza Colón s/n',
    lat: 41.6441,
    lon: -4.7319,
    keywords: ['hospital', 'campo grande', 'recoletas', 'colon', 'clinica'],
    icon: 'HeartPulse',
  },
  {
    id: 'poi_hosp_felipe_ii',
    name: 'Hospital Recoletas Felipe II',
    shortName: 'Hospital Felipe II',
    category: 'hospital',
    address: 'Calle Felipe II 9',
    lat: 41.6593,
    lon: -4.7231,
    keywords: ['hospital', 'felipe ii', 'recoletas', 'clinica'],
    icon: 'HeartPulse',
  },
  {
    id: 'poi_cs_parquesol',
    name: 'Centro de Salud Parquesol',
    shortName: 'C.S. Parquesol',
    category: 'hospital',
    address: 'Calle Ciudad de la Habana 17',
    lat: 41.6402,
    lon: -4.7671,
    keywords: ['centro de salud', 'parquesol', 'medico', 'habana'],
    icon: 'HeartPulse',
  },
  {
    id: 'poi_cs_delicias',
    name: 'Centro de Salud Delicias I y II',
    shortName: 'C.S. Delicias',
    category: 'hospital',
    address: 'Paseo Juan Carlos I 20',
    lat: 41.6385,
    lon: -4.7178,
    keywords: ['centro de salud', 'delicias', 'juan carlos i', 'medico'],
    icon: 'HeartPulse',
  },
  {
    id: 'poi_cs_plaza_ejercito',
    name: 'Centro de Salud Plaza del Ejército',
    shortName: 'C.S. Plaza del Ejército',
    category: 'hospital',
    address: 'Plaza del Ejército s/n',
    lat: 41.6375,
    lon: -4.7368,
    keywords: ['centro de salud', 'plaza ejercito', 'zorrilla', 'medico'],
    icon: 'HeartPulse',
  },

  // --- CENTROS COMERCIALES Y TIENDAS ---
  {
    id: 'poi_cc_vallsur',
    name: 'Centro Comercial Vallsur',
    shortName: 'CC Vallsur',
    category: 'comercial',
    address: 'Paseo de Zorrilla s/n',
    lat: 41.6166,
    lon: -4.7483,
    keywords: ['vallsur', 'centro comercial', 'compras', 'tiendas', 'cine', 'carrefour', 'zorrilla'],
    icon: 'ShoppingBag',
  },
  {
    id: 'poi_cc_rio_shopping',
    name: 'Centro Comercial Río Shopping (IKEA)',
    shortName: 'CC Río Shopping',
    category: 'comercial',
    address: 'Calle Me Falta un Tornillo 3',
    lat: 41.6258,
    lon: -4.7735,
    keywords: ['rio shopping', 'ikea', 'centro comercial', 'compras', 'tiendas', 'primark', 'cine', 'arroyo'],
    icon: 'ShoppingBag',
  },
  {
    id: 'poi_corte_ingles_zorrilla',
    name: 'El Corte Inglés (Paseo de Zorrilla)',
    shortName: 'El Corte Inglés (Zorrilla)',
    category: 'comercial',
    address: 'Paseo de Zorrilla 130',
    lat: 41.6315,
    lon: -4.7431,
    keywords: ['corte ingles', 'zorrilla', 'hipercor', 'compras', 'tiendas'],
    icon: 'ShoppingBag',
  },
  {
    id: 'poi_corte_ingles_constitucion',
    name: 'El Corte Inglés (Calle Constitución)',
    shortName: 'El Corte Inglés (Centro)',
    category: 'comercial',
    address: 'Calle Constitución 2',
    lat: 41.6508,
    lon: -4.7282,
    keywords: ['corte ingles', 'constitucion', 'centro', 'compras', 'tiendas'],
    icon: 'ShoppingBag',
  },
  {
    id: 'poi_mercado_del_val',
    name: 'Mercado del Val',
    shortName: 'Mercado del Val',
    category: 'comercial',
    address: 'Plaza del Val s/n',
    lat: 41.6550,
    lon: -4.7275,
    keywords: ['mercado', 'val', 'gastronomia', 'tapas', 'compras'],
    icon: 'ShoppingBag',
  },

  // --- UNIVERSIDADES Y CAMPUS ---
  {
    id: 'poi_campus_miguel_delibes',
    name: 'Campus Universitario Miguel Delibes (UVa)',
    shortName: 'Campus Miguel Delibes',
    category: 'universidad',
    address: 'Paseo de Belén 1',
    lat: 41.6622,
    lon: -4.7058,
    keywords: ['uva', 'campus', 'miguel delibes', 'ciencias', 'teleco', 'educacion', 'universidad', 'belen'],
    icon: 'GraduationCap',
  },
  {
    id: 'poi_facultad_derecho',
    name: 'Facultad de Derecho - Plaza de la Universidad',
    shortName: 'Facultad de Derecho',
    category: 'universidad',
    address: 'Plaza de la Universidad s/n',
    lat: 41.6534,
    lon: -4.7212,
    keywords: ['uva', 'derecho', 'plaza universidad', 'universidad'],
    icon: 'GraduationCap',
  },
  {
    id: 'poi_facultad_medicina',
    name: 'Facultad de Medicina y Ciencias de la Salud',
    shortName: 'Facultad de Medicina',
    category: 'universidad',
    address: 'Avenida Ramón y Cajal 7',
    lat: 41.6578,
    lon: -4.7198,
    keywords: ['uva', 'medicina', 'enfermeria', 'ramon y cajal', 'universidad'],
    icon: 'GraduationCap',
  },
  {
    id: 'poi_ingenieros_cauce',
    name: 'Escuela de Ingenierías Industriales (Sede Cauce)',
    shortName: 'Industriales (Sede Cauce)',
    category: 'universidad',
    address: 'Paseo del Cauce 59',
    lat: 41.6570,
    lon: -4.7061,
    keywords: ['uva', 'industriales', 'ingenieria', 'cauce', 'universidad'],
    icon: 'GraduationCap',
  },
  {
    id: 'poi_ingenieros_mendizabal',
    name: 'Escuela de Ingenierías Industriales (Sede Mendizábal)',
    shortName: 'Industriales (Mendizábal)',
    category: 'universidad',
    address: 'Calle Francisco Mendizábal 1',
    lat: 41.6410,
    lon: -4.7460,
    keywords: ['uva', 'industriales', 'mendizabal', 'universidad'],
    icon: 'GraduationCap',
  },
  {
    id: 'poi_facultad_economicas',
    name: 'Facultad de Ciencias Económicas y Empresariales',
    shortName: 'Facultad de Económicas',
    category: 'universidad',
    address: 'Avenida Valle de Esgueva 6',
    lat: 41.6575,
    lon: -4.7095,
    keywords: ['uva', 'economicas', 'empresariales', 'valle esgueva', 'comercio', 'universidad'],
    icon: 'GraduationCap',
  },
  {
    id: 'poi_uemc',
    name: 'Universidad Europea Miguel de Cervantes (UEMC)',
    shortName: 'Universidad UEMC',
    category: 'universidad',
    address: 'Calle Padre Julio Chevalier 2',
    lat: 41.6212,
    lon: -4.7369,
    keywords: ['uemc', 'universidad europea', 'miguel de cervantes', 'chevalier'],
    icon: 'GraduationCap',
  },

  // --- PLAZAS, MONUMENTOS Y CENTRO HISTÓRICO ---
  {
    id: 'poi_plaza_mayor',
    name: 'Plaza Mayor de Valladolid',
    shortName: 'Plaza Mayor',
    category: 'monumento',
    address: 'Plaza Mayor s/n',
    lat: 41.6523,
    lon: -4.7285,
    keywords: ['plaza mayor', 'centro', 'ayuntamiento', 'conde ansurez', 'turismo', 'tapas'],
    icon: 'Landmark',
  },
  {
    id: 'poi_plaza_espana',
    name: 'Plaza de España',
    shortName: 'Plaza de España',
    category: 'monumento',
    address: 'Plaza de España s/n',
    lat: 41.6493,
    lon: -4.7262,
    keywords: ['plaza espana', 'plaza españa', 'centro', 'banco de espana', 'marquesina'],
    icon: 'Landmark',
  },
  {
    id: 'poi_plaza_zorrilla',
    name: 'Plaza Zorrilla / Academia de Caballería',
    shortName: 'Plaza Zorrilla',
    category: 'monumento',
    address: 'Plaza Zorrilla s/n',
    lat: 41.6475,
    lon: -4.7303,
    keywords: ['plaza zorrilla', 'caballeria', 'campo grande', 'centro'],
    icon: 'Landmark',
  },
  {
    id: 'poi_campo_grande',
    name: 'Parque Campo Grande',
    shortName: 'Campo Grande',
    category: 'monumento',
    address: 'Paseo de Zorrilla s/n',
    lat: 41.6449,
    lon: -4.7307,
    keywords: ['campo grande', 'parque', 'pavos reales', 'paseo zorrilla', 'palomar'],
    icon: 'Trees',
  },
  {
    id: 'poi_plaza_san_pablo',
    name: 'Plaza de San Pablo y Palacio Real',
    shortName: 'Plaza de San Pablo',
    category: 'monumento',
    address: 'Plaza de San Pablo s/n',
    lat: 41.6575,
    lon: -4.7244,
    keywords: ['san pablo', 'palacio real', 'iglesia san pablo', 'capitania', 'corte'],
    icon: 'Landmark',
  },
  {
    id: 'poi_catedral',
    name: 'Catedral de Nuestra Señora de la Asunción',
    shortName: 'Catedral de Valladolid',
    category: 'monumento',
    address: 'Calle Arribas 1',
    lat: 41.6531,
    lon: -4.7236,
    keywords: ['catedral', 'arribas', 'la seo', 'herrera', 'monumento', 'iglesia'],
    icon: 'Landmark',
  },
  {
    id: 'poi_teatro_calderon',
    name: 'Teatro Calderón de Valladolid',
    shortName: 'Teatro Calderón',
    category: 'monumento',
    address: 'Calle Angustias 1',
    lat: 41.6548,
    lon: -4.7241,
    keywords: ['teatro calderon', 'seminci', 'angustias', 'opera', 'cultura'],
    icon: 'Landmark',
  },
  {
    id: 'poi_museo_escultura',
    name: 'Museo Nacional de Escultura (San Gregorio)',
    shortName: 'Museo de Escultura',
    category: 'monumento',
    address: 'Calle Cadenas de San Gregorio 1',
    lat: 41.6578,
    lon: -4.7229,
    keywords: ['museo escultura', 'san gregorio', 'berruguete', 'arte', 'cultura'],
    icon: 'Landmark',
  },
  {
    id: 'poi_museo_ciencia',
    name: 'Museo de la Ciencia de Valladolid',
    shortName: 'Museo de la Ciencia',
    category: 'monumento',
    address: 'Avenida de Salamanca 59',
    lat: 41.6364,
    lon: -4.7472,
    keywords: ['museo de la ciencia', 'planetario', 'avenida salamanca', 'pisuerga'],
    icon: 'Landmark',
  },
  {
    id: 'poi_cupula_milenio',
    name: 'Cúpula del Milenio',
    shortName: 'Cúpula del Milenio',
    category: 'monumento',
    address: 'Plaza del Milenio 1',
    lat: 41.6502,
    lon: -4.7380,
    keywords: ['cupula milenio', 'plaza milenio', 'puente isabel la catolica', 'rio pisuerga'],
    icon: 'Landmark',
  },
  {
    id: 'poi_playa_moreras',
    name: 'Playa de las Moreras',
    shortName: 'Playa de las Moreras',
    category: 'monumento',
    address: 'Paseo de Marcelino Martín El Chato s/n',
    lat: 41.6558,
    lon: -4.7371,
    keywords: ['playa moreras', 'moreras', 'rio pisuerga', 'parque moreras', 'ocio'],
    icon: 'Trees',
  },

  // --- DEPORTES Y EVENTOS ---
  {
    id: 'poi_estadio_zorrilla',
    name: 'Estadio Municipal José Zorrilla (Real Valladolid)',
    shortName: 'Estadio José Zorrilla',
    category: 'deporte',
    address: 'Avenida del Mundial 82 s/n',
    lat: 41.6443,
    lon: -4.7611,
    keywords: ['estadio zorrilla', 'real valladolid', 'futbol', 'pucela', 'partido'],
    icon: 'Trophy',
  },
  {
    id: 'poi_polideportivo_pisuerga',
    name: 'Polideportivo Pisuerga',
    shortName: 'Polideportivo Pisuerga',
    category: 'deporte',
    address: 'Plaza México s/n',
    lat: 41.6322,
    lon: -4.7495,
    keywords: ['pisuerga', 'baloncesto', 'conciertos', 'deporte', 'pabellon'],
    icon: 'Trophy',
  },
  {
    id: 'poi_polideportivo_huerta_rey',
    name: 'Polideportivo Huerta del Rey',
    shortName: 'Huerta del Rey (Pabellón)',
    category: 'deporte',
    address: 'Calle Joaquín Velasco Martín 9',
    lat: 41.6499,
    lon: -4.7420,
    keywords: ['huerta del rey', 'balonmano', 'atletico valladolid', 'pabellon', 'deporte'],
    icon: 'Trophy',
  },
  {
    id: 'poi_auditorio_delibes',
    name: 'Centro Cultural Miguel Delibes (Auditorio)',
    shortName: 'Auditorio Miguel Delibes',
    category: 'deporte',
    address: 'Avenida del Real Valladolid 2',
    lat: 41.6409,
    lon: -4.7621,
    keywords: ['auditorio', 'conciertos', 'miguel delibes', 'sinfonica', 'musica', 'cultura'],
    icon: 'Landmark',
  },
  {
    id: 'poi_feria_valladolid',
    name: 'Feria de Valladolid',
    shortName: 'Feria de Valladolid',
    category: 'deporte',
    address: 'Avenida Ramón Pradera 3',
    lat: 41.6526,
    lon: -4.7438,
    keywords: ['feria de valladolid', 'muestrario', 'exposiciones', 'congresos', 'ramon pradera'],
    icon: 'Landmark',
  },

  // --- SERVICIOS PÚBLICOS ---
  {
    id: 'poi_ayuntamiento',
    name: 'Ayuntamiento de Valladolid',
    shortName: 'Ayuntamiento',
    category: 'servicios',
    address: 'Plaza Mayor 1',
    lat: 41.6526,
    lon: -4.7284,
    keywords: ['ayuntamiento', 'casa consistorial', 'alcaldia', 'plaza mayor', 'tramites'],
    icon: 'Building2',
  },
  {
    id: 'poi_junta_cyl',
    name: 'Sede Central de la Junta de Castilla y León',
    shortName: 'Junta de Castilla y León',
    category: 'servicios',
    address: 'Calle Santiago Alba 1',
    lat: 41.6446,
    lon: -4.7455,
    keywords: ['junta', 'castilla y leon', 'gobierno autonomico', 'santiago alba'],
    icon: 'Building2',
  },
  {
    id: 'poi_juzgados_angustias',
    name: 'Palacio de Justicia / Juzgados de Valladolid',
    shortName: 'Juzgados (Angustias)',
    category: 'servicios',
    address: 'Calle Angustias 40',
    lat: 41.6555,
    lon: -4.7230,
    keywords: ['juzgados', 'justicia', 'audiencia provincial', 'angustias'],
    icon: 'Building2',
  },

  // --- BARRIOS Y PLAZAS CLAVE ---
  {
    id: 'poi_barrio_parquesol',
    name: 'Parquesol (Plaza Marcos Fernández)',
    shortName: 'Parquesol (Centro)',
    category: 'barrio',
    address: 'Plaza Marcos Fernández',
    lat: 41.6378,
    lon: -4.7628,
    keywords: ['parquesol', 'marcos fernandez', 'barrio'],
    icon: 'MapPin',
  },
  {
    id: 'poi_barrio_delicias',
    name: 'Delicias (Plaza del Carmen)',
    shortName: 'Delicias (Plaza del Carmen)',
    category: 'barrio',
    address: 'Plaza del Carmen',
    lat: 41.6372,
    lon: -4.7188,
    keywords: ['delicias', 'plaza del carmen', 'barrio'],
    icon: 'MapPin',
  },
  {
    id: 'poi_barrio_victoria',
    name: 'La Victoria (Plaza de San Bartolomé)',
    shortName: 'La Victoria',
    category: 'barrio',
    address: 'Plaza de San Bartolomé',
    lat: 41.6653,
    lon: -4.7348,
    keywords: ['la victoria', 'san bartolome', 'barrio'],
    icon: 'MapPin',
  },
  {
    id: 'poi_barrio_rondilla',
    name: 'La Rondilla (Plaza Alberto Fernández)',
    shortName: 'La Rondilla',
    category: 'barrio',
    address: 'Plaza Alberto Fernández',
    lat: 41.6631,
    lon: -4.7265,
    keywords: ['rondilla', 'alberto fernandez', 'barrio'],
    icon: 'MapPin',
  },
  {
    id: 'poi_barrio_circular',
    name: 'Plaza Circular / Vadillos',
    shortName: 'Plaza Circular',
    category: 'barrio',
    address: 'Plaza Circular',
    lat: 41.6468,
    lon: -4.7170,
    keywords: ['plaza circular', 'circular', 'vadillos', 'tudela'],
    icon: 'MapPin',
  },
  {
    id: 'poi_barrio_covaresa',
    name: 'Covaresa (Plaza Castilla y León)',
    shortName: 'Covaresa',
    category: 'barrio',
    address: 'Plaza Castilla y León',
    lat: 41.6115,
    lon: -4.7535,
    keywords: ['covaresa', 'castilla y leon', 'barrio', 'sur'],
    icon: 'MapPin',
  },
  {
    id: 'poi_barrio_rubia',
    name: 'La Rubia (Carretera de Rueda)',
    shortName: 'La Rubia',
    category: 'barrio',
    address: 'Carretera de Rueda con Paseo Zorrilla',
    lat: 41.6245,
    lon: -4.7432,
    keywords: ['la rubia', 'rueda', 'zorrilla', 'barrio'],
    icon: 'MapPin',
  },
  {
    id: 'poi_barrio_pilarica',
    name: 'Pilarica / Paseo Juan Carlos I',
    shortName: 'Pilarica',
    category: 'barrio',
    address: 'Paseo Juan Carlos I con Calle Puente la Reina',
    lat: 41.6542,
    lon: -4.7088,
    keywords: ['pilarica', 'puente la reina', 'barrio'],
    icon: 'MapPin',
  },
];
